<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-MDC2CVU" failures="1" tests="7" name="Default test" time="10.979" errors="0" timestamp="28 Jan 2018 01:28:09 GMT">
  <testcase classname="cucumber.api.testng.AbstractTestNGCucumberTests" name="feature" time="0.013"/>
  <testcase classname="cucumber.api.testng.AbstractTestNGCucumberTests" name="feature" time="0.002"/>
  <testcase classname="cucumber.api.testng.AbstractTestNGCucumberTests" name="feature" time="0.004"/>
  <testcase classname="cucumber.api.testng.AbstractTestNGCucumberTests" name="feature" time="0.002"/>
  <testcase classname="com.revature.tests.trainer.TestBatches" name="TestLocations" time="3.45">
    <failure type="java.lang.AssertionError" message="Revature HQ and/or New York City drop downs not found. Not in Locations tab">
      <![CDATA[java.lang.AssertionError: Revature HQ and/or New York City drop downs not found. Not in Locations tabat org.testng.Assert.fail(Assert.java:96)at com.revature.tests.trainer.TestBatches.TestLocations(TestBatches.java:42)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.base/java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- TestLocations -->
  <testcase classname="com.revature.tests.trainer.TestBatches" name="TestOne" time="3.374"/>
  <testcase classname="com.revature.tests.trainer.TestBatches" name="TestTwo" time="3.155"/>
</testsuite> <!-- Default test -->
